version: '3'
services:
  app:
    image: ai-hoops
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - FRAME_BUFFER_SIZE=6 # the # of frames to buffer before emitting to client.
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 --workers 1 --worker-class eventlet -t 120 app:app
    volumes:
      - .:/app  # Mount the current directory to /app in the container