version: '3'
services:
  app:
    image: ai-hoops
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - SOLO_FRAME_BUFFER_SIZE=3 # the # of frames to buffer before emitting to client for solo mode
      - AI_FRAME_BUFFER_SIZE= 10 # the # of frames to buffer before emitting to client for AI mode (training and record model) TODO: simulate entire game very quickly and make this less choppy.
      - TARGET_FRAME_RATE=80 # the target frame rate for the video stream.
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 --workers 1 --worker-class eventlet -t 120 app:app
    volumes:
      - .:/app  # Mount the current directory to /app in the container